
---
title: "kuntar"
output: github_document
author: "Meeri Seppä"
---


Project structure:


  
| *input*                                    | *filename *        | *output*  |
|------------------------------------------|------------------|----------------------|
| (old shapefiles)                         |   create_ids     | ids.csv,  kartoissa_olevat_kunnat.csv, lakkautetut_kunnnat_2019_tilastokesku.csv, olemassa_olevat_kunnnat_2019.csv|
|old shapefiles,  ids.csv  | fix_maps    |   mapfiles, mapfiles_fixed|
|mapfiles_fixed    |  remove_overlaps    | mapfiles_fixed_no_overlaps |
|mapfiles_fixed_no_overlaps |    create_changes   |   kuntamuutokset_1860_1970.csv|
|mapfiles_fixed_no_overlaps, kuntamuutokset_1860_1970.csv,                      lakkautetut_kunnnat_2019_tilastokeskus.csv |   remove_errors | mapfiles_fixed_no_overlaps_or_errors,  new_shapfiles (kunnat) |
|mapfiles_fixed_no_overlaps_or_errors | update_changes | kuntamuutokset_1860_1970_no_errors.csv |
| mapfiles_fixed_no_overlaps_or_errors, kuntamuutokset_1860_1970.csv | create_consistent|new_shapefiles (consistent) |
|mapfiles_fixed_no_overlaps_or_errors	| create_crosswalk |  crosswalk_files|
|shapefiles (2013-2019)  |  create_mapfiles_00  | mapfiles_00 |
|ids.csv   | create_leikkidata  | leikkidata_1930.csv, leikkidata_1970.csv |



These files contain functions that are used in the scripts above:

-	functions.R
-	functions_fix_maps.R
-	functions_consistent




This file will update every dataset:

- update_files.R



The web page:

- app.R 

Instructions for the webpage:

- intructions